<a href="https://colab.research.google.com/github/Sneha11019/DevOpsLab2/blob/main/4NI25CS195_EXP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:",pd.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.3

In [ ]:
marks=np.array([78,88,99,92,65])
print("Marks:",marks)
print("Type:",type(marks))

Marks: [78 88 99 92 65]
Type: <class 'numpy.ndarray'>

In [ ]:
print("Number of dimensions:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)

Number of dimensions: 1
Shape: (5,)
Number of elements: 5

In [ ]:
marks=np.array([78,88,99,92,65])
print("original:",marks)
print("add 5:",marks+5)
print("multiply by 2:",marks*2)
print("divide by 2",marks/2)
print("square:",marks**2)

original: [78 88 99 92 65]
add 5: [ 83  93 104  97  70]
multiply by 2: [156 176 198 184 130]
divide by 2 [39.  44.  49.5 46.  32.5]
square: [6084 7744 9801 8464 4225]

In [ ]:
marks=np.array([78,88,99,92,65])
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum",marks.min())

Sum: 422
Mean: 84.4
Maximum: 99
Minimum 65

In [ ]:
print("First mark:",marks[0])
print("Second mark:",marks[1])
print("Last mark:",marks[-1])

First mark: 78
Second mark: 88
Last mark: 65

In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[2:])
print("Every second element:",marks[::2])

Index 1 to 3: [88 99 92]
First three: [78 88 99]
From index 2: [99 92 65]
Every second element: [78 99 65]

In [ ]:
student_marks= np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)

In [ ]:
print("Mean of all values:",student_marks.mean())
print("Column-wise mean:",student_marks.mean(axis=0))
print("Row-wise mean:",student_marks.mean(axis=1))

Mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
Row-wise mean: [85.         77.         91.33333333]

In [ ]:
data={
    "Name":["Anu","Rahul","KIran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}
df=pd.DataFrame(data)
df

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  KIran    CSE     76
3  Priya   AIML     88

In [ ]:
print("Shape:",df.shape)
print("\nColumns:")
print(df.columns)

Shape: (4, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.head()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  KIran    CSE     76
3  Priya   AIML     88

In [ ]:
df.tail()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  KIran    CSE     76
3  Priya   AIML     88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           Marks
count   4.000000
mean   85.000000
std     6.480741
min    76.000000
25%    82.750000
50%    86.500000
75%    88.750000
max    91.000000

In [ ]:
print("Marks column")
print(df["Marks"])
print("\nBranch and Marks:")
print(df[["Branch","Marks"]])

Marks column
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

Branch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88

In [ ]:
print("First row:")
print(df.iloc[0])

print("\nSecond row:")
print(df.iloc[1])

print("\nFirst three rows:")
print(df.iloc[0:3])

print("First two rows first two columns:")
print(df.iloc[0:2,0:2])

First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  KIran    CSE     76
First two rows first two columns:
    Name Branch
0    Anu    CSE
1  Rahul   AIML

In [ ]:
print("First three rows:")
display(df.iloc[0:3])

print("Rows 1 to 3, Nmae and Marks")
display(df.iloc[1:4, 0:3])

First three rows:

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  KIran    CSE     76

Rows 1 to 3, Nmae and Marks

    Name Branch  Marks
1  Rahul   AIML     91
2  KIran    CSE     76
3  Priya   AIML     88

In [ ]:
high_scorers=df[df["Marks"]>90]
high_scorers

    Name Branch  Marks
1  Rahul   AIML     91

In [ ]:
print("Students from CSE:")
display(df[df["Branch"] == "CSE"])

Students from CSE:

    Name Branch  Marks
0    Anu    CSE     85
2  KIran    CSE     76

In [ ]:
print("Students scoring 85 or above:")
display(df[df["Marks"]>=85])

Students scoring 85 or above:

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [ ]:
data={
    "Name":["Asha","Bharat","Chetan","Divya","Esha"],
    "Department":["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,95,68],
    "Attendance":[82,94,88,96,75]
}
students=pd.DataFrame(data)
students

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96
4    Esha        ISE     68          75

In [ ]:
print("Name")
print(students[["Name","Marks"]])
print("Marks")
print(students["Marks"])
print("student scoring more than 80",df[df["Marks"]>80])
print("First three Students",df.iloc[0:3])
display(students[students["Department"] == "CSE"])
print("mean",students["Marks"].mean())
print("maximum",students["Marks"].max())
display(
    students[(students["Marks"]>=80 &
                          (students["Attendance"]>85))]
)

Name
     Name  Marks
0    Asha     72
1  Bharat     91
2  Chetan     84
3   Divya     95
4    Esha     68
Marks
0    72
1    91
2    84
3    95
4    68
Name: Marks, dtype: int64
student scoring more than 80     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88
First three Students     Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  KIran    CSE     76

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
2  Chetan        CSE     84          88

mean 82.0
maximum 95

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96
4    Esha        ISE     68          75

In [ ]:
display(students[students["Department"] == "CSE"])

KeyError: 'Department'